spring:
  application:
    name: services-order
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: CloudProject-dev
        group: DEFAULT_GROUP
#      discovery:
#        enabled: true
#        server-addr: 127.0.0.1:8848
#        namespace: CloudProject-dev
#        group: DEFAULT_GROUP
server:
  port: 10001